name: CI

on:
  push:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: pnpm/action-setup@v6.0.9

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: "lts/*"
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Test coverage
        run: pnpm test:coverage

      - name: Lint
        run: pnpm lint
